Install
If a destination directory was specified with the "-d" flag, it was not used
=> Fix use of custom destination directory

src/_sass/gnome-shell/_common.scss
This makes it looking way more nicer.
**Before:**
**After:**
=> Enlarge a bit the general font-size for gnome-shell

src/gnome-shell/theme/gnome-shell.css
Removed the opinionated font selection to follow GNOME 3.36's shell font changes.
I only edited one CSS file to see if you like the change. If you do, the other CSS files would need to be changed too, of course.
=> Respect interface font

README.md
Both RHEL/CentOS (as of version 8, if I recall correctly) and Fedora have moved on from yum to dnf, so I think it is reasonable to change this to reflect that.
=> Change yum to dnf

src/_sass/gnome-shell/_common.scss
Gnome updated the class names for the clock and date elements in the lock screen.
Before:
After:
=> Fixed lock screen clock

src/_sass/gnome-shell/_common.scss
In polkit when asking for the user password `user-` was repeated in the selector.
The icon now is a circle and looks clearer.
Before:
After:
=> Fixed polkit user icon

src/_sass/gnome-shell/_common.scss
The password textbox and back button in the login and lock screens have weird dimensions. Also the user name not centered its moved a bit to the right.
This fixes them to more comfortable dimensions.
Before:
After:
=> Resized login inputs

src/_sass/gnome-shell/_common.scss, src/gnome-shell/gnome-shell-theme.gresource.xml, src/gnome-shell/theme-manjaro/gnome-shell-dark.css, src/gnome-shell/theme-manjaro/gnome-shell-light.css, src/gnome-shell/theme-manjaro/gnome-shell.css, src/gnome-shell/theme-ubuntu/gnome-shell-dark.css, src/gnome-shell/theme-ubuntu/gnome-shell-light.css, src/gnome-shell/theme-ubuntu/gnome-shell.css, src/gnome-shell/theme/gnome-shell-dark.css, src/gnome-shell/theme/gnome-shell-light.css, src/gnome-shell/theme/gnome-shell.css
Gnome-shell shows this warning `Failed to open sliced image: The resource at “/org/gnome/shell/theme/process-working.svg” does not exist`. It has hard coded that path for that icon.
It is used by things like the login screen and in the panel when opening an application, so it cannot be changed in the css.
=> Fix gnome-shell spinner

src/_sass/gnome-shell/_common.scss, src/gnome-shell/theme-manjaro/gnome-shell-dark.css, src/gnome-shell/theme-manjaro/gnome-shell-light.css, src/gnome-shell/theme-manjaro/gnome-shell.css, src/gnome-shell/theme-ubuntu/gnome-shell-dark.css, src/gnome-shell/theme-ubuntu/gnome-shell-light.css, src/gnome-shell/theme-ubuntu/gnome-shell.css, src/gnome-shell/theme/gnome-shell-dark.css, src/gnome-shell/theme/gnome-shell-light.css, src/gnome-shell/theme/gnome-shell.css
Gnome-shell shows this warning `Ignoring length property that isn't a number at line 1477, col 24`.
It doesn't support keywords for `background-position` and ignores these values.
=> Fix length warning

src/_sass/gnome-shell/_extensions.scss, src/gnome-shell/theme-manjaro/gnome-shell-dark.css, src/gnome-shell/theme-manjaro/gnome-shell-light.css, src/gnome-shell/theme-manjaro/gnome-shell.css, src/gnome-shell/theme-ubuntu/gnome-shell-dark.css, src/gnome-shell/theme-ubuntu/gnome-shell-light.css, src/gnome-shell/theme-ubuntu/gnome-shell.css, src/gnome-shell/theme/gnome-shell-dark.css, src/gnome-shell/theme/gnome-shell-light.css, src/gnome-shell/theme/gnome-shell.css
Dash to dock window preview was offset and it could even overflow.
Before:
Aflter:
=> Center dash to dock window preview

src/_sass/gnome-shell/_extensions.scss, src/gnome-shell/theme-manjaro/gnome-shell-dark.css, src/gnome-shell/theme-manjaro/gnome-shell-light.css, src/gnome-shell/theme-manjaro/gnome-shell.css, src/gnome-shell/theme-ubuntu/gnome-shell-dark.css, src/gnome-shell/theme-ubuntu/gnome-shell-light.css, src/gnome-shell/theme-ubuntu/gnome-shell.css, src/gnome-shell/theme/gnome-shell-dark.css, src/gnome-shell/theme/gnome-shell-light.css, src/gnome-shell/theme/gnome-shell.css
When using dash to dock dynamic transparency with Qogir it didn't respect the alphas and used full opacity.
Before:
After:
=> Fix dash to dock transparency

src/gnome-shell/common-assets/activities-active.svg
When trying to install the GDM theme, I would get this error (on manjaro):
```console
/.../Qogir-theme/src/gnome-shell/gnome-shell-theme.gresource.xml: Failed to locate “assets/activities-active.svg” in any source directory.
```
This PR copies the activities-active.svg from the cinnamon folder to the gnome-shell folder. Since the activities.svg is also just a copy, I'm assuming this should be the right icon.
=> activities-active.svg for gnome-shell assets

src/_sass/gtk/_darksidebar_widgets.scss, src/gtk/theme-3.0/gtk-Dark.css, src/gtk/theme-3.0/gtk-Light.css, src/gtk/theme-3.0/gtk.css
The close button in nautilus is not correctly aligned when using the window buttons on the left.
Before
After
=> Align nautilus window buttons

src/_sass/gnome-shell/widgets-common/_login-dialog.scss, src/gnome-shell/theme-3-32/gnome-shell-Dark.css, src/gnome-shell/theme-3-32/gnome-shell.css, src/gnome-shell/theme-40-0/gnome-shell-Dark.css, src/gnome-shell/theme-40-0/gnome-shell.css, src/gnome-shell/theme-42-0/gnome-shell-Dark.css, src/gnome-shell/theme-42-0/gnome-shell.css
Tried to match the controls to the rest of the theme. They are more squared and a bit easier to see the buttons.
Before
After
=> Update login screen

src/_sass/_colors.scss, src/_sass/gnome-shell/_widgets-42-0.scss, src/_sass/gnome-shell/widgets-common/_screenshot.scss, src/gnome-shell/theme-3-32/gnome-shell-Dark.css, src/gnome-shell/theme-3-32/gnome-shell.css, src/gnome-shell/theme-40-0/gnome-shell-Dark.css, src/gnome-shell/theme-40-0/gnome-shell.css, src/gnome-shell/theme-42-0/gnome-shell-Dark.css, src/gnome-shell/theme-42-0/gnome-shell.css
The screenshot UI was missing and it was basically transparent. It also matches the rounded corners if the tweak is installed.
Fixes #235
=> Add screenshot UI support

src/_sass/gnome-shell/widgets-common/_slider.scss, src/_sass/gnome-shell/widgets-common/_switches.scss, src/gnome-shell/gnome-shell-theme.gresource.xml, src/gnome-shell/theme-3-32/gnome-shell-Dark.css, src/gnome-shell/theme-3-32/gnome-shell.css, src/gnome-shell/theme-40-0/gnome-shell-Dark.css, src/gnome-shell/theme-40-0/gnome-shell.css, src/gnome-shell/theme-42-0/gnome-shell-Dark.css, src/gnome-shell/theme-42-0/gnome-shell.css
When moving the mouse outside of the selected item the highlight was not visible.
Before:
After:
=> Fix popup menu selected colors

install.sh
The `IconTheme` value is set to the same value as the theme. This is incorrect, as the icon themes are named using lowercase. For example: the icon theme for `Qogir-Ubuntu-Dark` is named `Qogir-ubuntu-dark`.
Fix this by setting the `IconTheme` to the correct lowercase equivalent.
=> Fix icon theme case in theme definition

install.sh
When using the `--tweaks round` option, `install.sh` exits after attempting to install sassc. I believe it's because apt is waiting for the user to input `yes`. I added the `assume-yes` option in the command for apt. Don't know if it happens on other distros.
=> fix program exiting after trying to install sassc on Debian

src/_sass/gnome-shell/widgets-42-0/_quick-settings.scss, src/gnome-shell/theme-42-0/gnome-shell-Dark.css, src/gnome-shell/theme-42-0/gnome-shell.css
In GNOME 43 the icon sizes of the toggles in the quick settings was too big. This only happened when installing as gdm theme.
Before:
After:
=> Fix toggle icon size

src/_sass/cinnamon/_common.scss
When cinnamon text scaling or text sizes are bigger than the default, text does not fit in menu applet search entry or menu-selected-app-box so remove height limit to allow automatic widget sizing.
Fixes: https://github.com/linuxmint/cinnamon/issues/12126
=> common.scss: fix menu applet text dpi bug

install.sh
Previously [`install.sh`](https://github.com/vinceliuice/Qogir-theme/blob/master/install.sh) would fail to run [`clean-old-theme.sh`](https://github.com/vinceliuice/Qogir-theme/blob/master/clean-old-theme.sh) unless launched from the source directory:
```bash
~ $ cd ~
~ $ /tmp/Qogir-theme-master/install.sh
'gnome-shell' not found, using styles for last gnome-shell version available.
/tmp/Qogir-theme-master/install.sh: line 722: ./clean-old-theme.sh: No such file or directory
Installing '/home/sidroberts/.themes/Qogir'...
Installing '/home/sidroberts/.themes/Qogir-Light'...
Installing '/home/sidroberts/.themes/Qogir-Dark'...
Done.
```
=> clean-old-theme.sh is executed properly when running install.sh from another directory

src/_sass/gnome-shell/widgets-42-0/_quick-settings.scss, src/gnome-shell/theme-42-0/gnome-shell-Dark.css, src/gnome-shell/theme-42-0/gnome-shell.css
The arrows in the quick settings were disproportionally big.
This only happens when installed as gdm theme.
Before:
After:
=> Fix quick settings arrow size

src/_sass/_colors.scss, src/_sass/gnome-shell/_drawing.scss, src/_sass/gnome-shell/widgets-common/_panel.scss, src/gnome-shell/theme-3-32/gnome-shell-Dark.css, src/gnome-shell/theme-3-32/gnome-shell.css, src/gnome-shell/theme-40-0/gnome-shell-Dark.css, src/gnome-shell/theme-40-0/gnome-shell.css, src/gnome-shell/theme-42-0/gnome-shell-Dark.css, src/gnome-shell/theme-42-0/gnome-shell.css, src/gnome-shell/theme-44-0/gnome-shell-Dark.css, src/gnome-shell/theme-44-0/gnome-shell.css, src/gnome-shell/theme-46-0/gnome-shell-Dark.css, src/gnome-shell/theme-46-0/gnome-shell.css
Default adwaita theme in gnome has colors to make it clear that screen is being recorded/shared. Also the icons where big compared to the rest.
This only happens when installed as gdm theme.
Before:
After:
Adwaita for reference:
=> Fix sharing indicators

src/_sass/gnome-shell/widgets-common/_popovers.scss, src/gnome-shell/theme-3-32/gnome-shell-Dark.css, src/gnome-shell/theme-3-32/gnome-shell.css, src/gnome-shell/theme-40-0/gnome-shell-Dark.css, src/gnome-shell/theme-40-0/gnome-shell.css, src/gnome-shell/theme-42-0/gnome-shell-Dark.css, src/gnome-shell/theme-42-0/gnome-shell.css, src/gnome-shell/theme-44-0/gnome-shell-Dark.css, src/gnome-shell/theme-44-0/gnome-shell.css, src/gnome-shell/theme-46-0/gnome-shell-Dark.css, src/gnome-shell/theme-46-0/gnome-shell.css
The separator item was being hidden. For example in the case of gsconnect it contains useful information.
This only happens when installed as gdm theme.
Before:
After:
=> Fix popup separator menu item

README.md, install.sh
When installing the theme with the parameter to install it as a dark theme (`-c dark`), the Adwaita linking fails, since it does not capture the right theme name. 
The README.md did not contain instructions on installing the dependencies for openSUSE.
In the terminal, run:
`./install.sh -c dark -i opensuse -l`
This works, but doesn't do any linking, since the theme is always selected as `Qogir-Light`.
The issue with installation happens because in `link_theme()` function, it had `COLOR_VARIANTS[1]` so it always took  '-Light'. This was changed to `colors[@]`. Subsequently I also changed `THEME_VARIANTS[0]` to `themes[@]` so that it also considers the right theme variant.
Added dependency installation instructions for openSUSE.
=> Script fix and readme update
